name: Daily Sync Sonarcube

# on:
#   schedule:
#     - cron: '0 0 * * 1-5'

on:
  push:
    branches:
      - chore/setup-sonarqube

jobs:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile # same as 'npm ci'
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=storyblok-design-system
            -Dsonar.scm.provider=git
            -Dsonar.sources=src/
            -Dsonar.exclusions=src/**/**.spec.js,src/**/**.specs.js,src/**/**.stories.js
            -Dsonar.tests=src/,tests/unit/
            -Dsonar.test.inclusions=src/**/**.spec.js,src/**/**.specs.js,tests/unit/**/**.spec.js
